version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8021:8021"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - DEBUG=True
      - DATABASE_URL=sqlite:///./data/visibility.db
      - BACKEND_CORS_ORIGINS=["http://localhost:3000"]
    env_file:
      - ./backend/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8021 --reload
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8021
    env_file:
      - ./frontend/.env
    command: npm run dev -- --host 0.0.0.0

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: visibility_tracker
      POSTGRES_USER: visibility_user
      POSTGRES_PASSWORD: visibility_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Service optionnel pour les tests
  test:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
      - DEBUG=True
    command: pytest
    profiles:
      - test

volumes:
  postgres_data: 